use serde::{Deserialize, Serialize};

use crate::llm::error::LlmError;

/// Safety level of a command
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum SafetyLevel {
    Safe,
    Caution,
    Dangerous,
}

impl std::fmt::Display for SafetyLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SafetyLevel::Safe => write!(f, "SAFE"),
            SafetyLevel::Caution => write!(f, "CAUTION"),
            SafetyLevel::Dangerous => write!(f, "DANGEROUS"),
        }
    }
}

/// Component of a command explanation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommandComponent {
    pub part: String,
    pub explanation: String,
}

/// Explanation of what a command does
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommandExplanation {
    pub purpose: String,
    pub components: Vec<CommandComponent>,
}

/// A command candidate generated by the LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommandCandidate {
    pub command: String,
    pub description: String,
    pub safety_level: SafetyLevel,
    pub explanation: CommandExplanation,
}

/// Result of command generation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommandGeneration {
    pub commands: Vec<CommandCandidate>,
    pub is_ambiguous: bool,
    pub additional_questions: Vec<String>,
    #[serde(skip)]
    pub raw_response: String,
}

/// Response from OpenAI API
#[derive(Debug, Deserialize)]
pub struct OpenAiResponse {
    pub id: String,
    pub object: String,
    pub created: u64,
    pub model: String,
    pub choices: Vec<OpenAiChoice>,
    pub usage: OpenAiUsage,
}

/// A single choice from OpenAI API response
#[derive(Debug, Deserialize)]
pub struct OpenAiChoice {
    pub index: usize,
    pub message: OpenAiMessage,
    pub finish_reason: String,
}

/// Message in OpenAI API response
#[derive(Debug, Deserialize)]
pub struct OpenAiMessage {
    pub role: String,
    pub content: String,
}

/// Usage information from OpenAI API
#[derive(Debug, Deserialize)]
pub struct OpenAiUsage {
    pub prompt_tokens: usize,
    pub completion_tokens: usize,
    pub total_tokens: usize,
}

impl CommandGeneration {
    /// Parse an OpenAI API response into a CommandGeneration
    pub fn from_openai_response(response: &OpenAiResponse) -> Result<Self, LlmError> {
        if response.choices.is_empty() {
            return Err(LlmError::ResponseParseError(
                "No choices in response".to_string(),
            ));
        }

        let content = &response.choices[0].message.content;
        Self::from_json_str(content)
    }

    /// Parse a JSON string into a CommandGeneration
    pub fn from_json_str(json_str: &str) -> Result<Self, LlmError> {
        let raw_response = json_str.to_string();

        // Try to parse as JSON
        let result: Result<CommandGeneration, _> = serde_json::from_str(json_str);

        match result {
            Ok(mut command_gen) => {
                command_gen.raw_response = raw_response;
                Ok(command_gen)
            }
            Err(e) => {
                // Try to extract JSON from a text response that might have additional content
                if let Some(json) = extract_json_from_text(json_str) {
                    let result: Result<CommandGeneration, _> = serde_json::from_str(&json);
                    match result {
                        Ok(mut command_gen) => {
                            command_gen.raw_response = raw_response;
                            Ok(command_gen)
                        }
                        Err(e) => Err(LlmError::ResponseParseError(format!(
                            "Failed to parse extracted JSON: {}",
                            e
                        ))),
                    }
                } else {
                    Err(LlmError::ResponseParseError(format!(
                        "Failed to parse response as JSON: {}",
                        e
                    )))
                }
            }
        }
    }
}

/// Try to extract JSON from text that might have additional content
fn extract_json_from_text(text: &str) -> Option<String> {
    // Look for a JSON object in the text
    if let Some(start) = text.find('{') {
        let mut depth = 0;
        let mut in_string = false;
        let mut escaped = false;

        for (i, c) in text[start..].char_indices() {
            if escaped {
                escaped = false;
                continue;
            }

            match c {
                '\\' if in_string => escaped = true,
                '"' => in_string = !in_string,
                '{' if !in_string => depth += 1,
                '}' if !in_string => {
                    depth -= 1;
                    if depth == 0 {
                        return Some(text[start..start + i + 1].to_string());
                    }
                }
                _ => {}
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_valid_json() {
        let json = r#"{
            "commands": [
                {
                    "command": "ls -la",
                    "description": "List all files in current directory with details",
                    "safety_level": "SAFE",
                    "explanation": {
                        "purpose": "Display detailed list of all files",
                        "components": [
                            {"part": "ls", "explanation": "List directory contents"},
                            {"part": "-la", "explanation": "Show hidden files and details"}
                        ]
                    }
                }
            ],
            "is_ambiguous": false,
            "additional_questions": []
        }"#;

        let result = CommandGeneration::from_json_str(json);
        assert!(result.is_ok());

        let command_gen = result.unwrap();
        assert_eq!(command_gen.commands.len(), 1);
        assert_eq!(command_gen.commands[0].command, "ls -la");
        assert_eq!(command_gen.commands[0].safety_level, SafetyLevel::Safe);
        assert_eq!(command_gen.is_ambiguous, false);
        assert_eq!(command_gen.additional_questions.len(), 0);
    }

    #[test]
    fn test_extract_json_from_text() {
        let text = r#"I'll help you list all files in your directory.

```json
{
  "commands": [
    {
      "command": "ls -la",
      "description": "List all files",
      "safety_level": "SAFE",
      "explanation": {
        "purpose": "Display files",
        "components": [
          {"part": "ls", "explanation": "List directory contents"},
          {"part": "-la", "explanation": "Show hidden files and details"}
        ]
      }
    }
  ],
  "is_ambiguous": false,
  "additional_questions": []
}
```

Let me know if you need anything else!"#;

        let json = extract_json_from_text(text);
        assert!(json.is_some());

        let result = CommandGeneration::from_json_str(&json.unwrap());
        assert!(result.is_ok());

        let command_gen = result.unwrap();
        assert_eq!(command_gen.commands.len(), 1);
        assert_eq!(command_gen.commands[0].command, "ls -la");
    }
}
